server.port=5000
server.address=0.0.0.0
# JPA 설정
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQLite 방언 설정 (com.github.gwenn 라이브러리 사용 시)
# spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.validator.apply_to_ddl=false
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
# SQLite는 외래 키 제약 조건을 제대로 지원하지 않으므로 비활성화
spring.jpa.properties.hibernate.foreign_keys=false